[package]
name = "deadman"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true
rust-version.workspace = true

[workspace]
resolver = "3"
members = ["pcap", "tcpip"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["cffnpwr <cffnpwr@gmail.com>"]
repository = "https://github.com/cffnpwr/deadman-rs.git"
license-file = "LICENSE"
rust-version = "1.85.0"

[workspace.dependencies]
anyhow = "1.0.98"
thiserror = "2.0.12"

[dependencies]
anyhow.workspace = true
tokio = { version = "1.45.1", features = ["macros", "rt", "rt-multi-thread", "signal"] }
pcap = { path = "./pcap", features = ["libpcap"] }
tcpip = { path = "./tcpip" }
