# 監視対象
targets = [
  # { name = 表示名, host = ホスト名 }
  { name = "loopback", host = "127.0.0.1" },
  { name = "Cloudflare Primary DNS", host = "1.1.1.1" },
  { name = "Cloudflare Secondary DNS", host = "1.0.0.1" },
  { name = "Google Primary DNS", host = "8.8.8.8" },
  { name = "Google Secondary DNS", host = "8.8.4.4" },
  { name = "RawIP Target (Tailscale DNS)", host = "100.100.100.100" },
  { name = "invalid", host = "123.45.67.89" },
]
# 監視間隔（秒）
interval = 1
# タイムアウト（秒）
timeout = 5

# Traceroute設定 - オプション
[traceroute]
# traceroute機能の有効/無効 - デフォルトtrue
enable = true
# 最大ホップ数 - デフォルト30
max_hops = 30

# ARP設定 - オプション
[arp]
# ARPテーブルのTTL（秒） - デフォルト30秒
ttl = 30
# ARP応答のタイムアウト（秒） - デフォルト5秒
timeout = 5
