shared-version = false
tag-name = "{{crate_name}}-v{{version}}"
tag-message = "Release {{crate_name}} v{{version}}"
publish = false
push = false
allow-branch = ["main", "release", "feature/*", "bugfix/*"]
pre-release-replacements = []
release = false
dependent-version = "ignore"